# Generated by Django 4.2.9 on 2025-09-13 08:50

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_deleted_at_message_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, default='https://ui-avatars.com/api/?background=random&name=User', help_text='Fallback avatar URL if no image is uploaded'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to=chat.models.user_directory_path),
        ),
    ]
